version: '3.7'
services:
  currency-conversion-ui:
    image: shefkjm/currency-conversion-ui:1.0
    ports:
      - "9093:80"
    restart: always
    environment:
      #Change it to the ip address of the machine you're running the application. For eg: 'http:\/\/34.125.197.10:9091\/api\/'
      CONVERSION_API_URL_REPLACE: 'http:\/\/localhost:9091\/api\/'
      RATES_API_URL_REPLACE: 'http:\/\/localhost:9092\/api\/'
    depends_on: # Start the depends_on first
      - exchange-rate-service
      - currency-conversion-service
    networks:
      - currency-conversion-network

  exchange-rate-service:
    image: shefkjm/exchange-rate-service:1.0
    ports:
      - "9092:9092"
    restart: always

    environment:
      DB_USER_NAME: shefkjm
      DB_PASSWORD: shef123
      SPRING_DATA_URL: jdbc:mysql://mysql:3306/exchange_rate?autoReconnect=true&useSSL=false
      PROFILE: sql
      PORT: 9092
      LOG_ENABLED: 'true'
      CRON_EXPRESSION: 0/5 * * ? * *
    depends_on: # Start the depends_on first
      - mysql
    networks:
      - currency-conversion-network
  currency-conversion-service:
    image: shefkjm/currency-conversion-service:1.0
    ports:
      - "9091:9091"
    restart: always

    environment:
      DB_USER_NAME: shefkjm
      DB_PASSWORD: shef123
      SPRING_DATA_URL: jdbc:mysql://mysql:3306/exchange_rate?autoReconnect=true&useSSL=false
      PROFILE: sql
      PORT: 9091
      EXCHANGE_RATE_URL: http://exchange-rate-service:9092
    depends_on: # Start the depends_on first
      - mysql

    networks:
      - currency-conversion-network
  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shefkjm
      MYSQL_PASSWORD: shef123
      MYSQL_DATABASE: exchange_rate
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - currency-conversion-network

# Volumes
volumes:
  mysql-database-data-volume:

networks:
  currency-conversion-network: