apiVersion: v1
kind: ResourceQuota
metadata:
  name: count-quotas
spec:
  hard:
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    requests.cpu: "1000m"
    limits.cpu: "2000m"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: secrets-counts
spec:
  hard:
    secrets: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.nvidia.com/gpu: 4
    persistentvolumeclaims: "1"
    services.loadbalancers: "2"
    services.nodeports: "0"
---
#Pod example
apiVersion: v1
kind: Pod
metadata:
  name: quota-pod-1
spec:
  containers:
  - name: quota-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Pod is Running ; sleep 3600']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
---
#syntax 1
#spec:
#  hard:
#    count/pods: "2"
#    count/secrets: "2"
#syntax 2
#spec:
#  hard:
#    pods: "2"
#    secrets: "2"