#Lets create docker registry with the help of secrets as mentioned below:
# If you don't already have a .dockercfg file, you can create a dockercfg secret directly by using:
kubectl create secret docker-registry my-secret --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL

Example:
kubectl create secret docker-registry my-docker --docker-server='https://index.docker.io/v1/' --docker-username=dubareddy --docker-password=XXXXXX --docker-email=sudhams.duba@gmail.com

apiVersion: v1
kind: Pod
metadata:
  name: ansible
  namespace: default
spec:
  containers:
  - name: ansible
    image: dubareddy/ansibleserver:2.16
    imagePullPolicy: Always #IfNotPresent, Never
  imagePullSecrets:
    - name: my-docker

#Inorder to see the output: kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode