apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80    #Port of the Container exposed for nginx application
  volumes:
  - name: nginx-storage
    persistentVolumeCliam:
      claimName: pv-claim