apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyber
  namespace: cyber
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1 #rbac.authorization.k8s.io/v1beta1(removed before 1.22)
metadata:
  name: mynamespace-user-full-access
  namespace: cyber
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "deployments", 'configmaps']
  verbs: ["get", "create", "list"]       #["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mynamespace-user-view
  namespace: cyber
subjects:
- kind: ServiceAccount #user, group
  name: cyber
  namespace: cyber
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mynamespace-user-full-access