#Pod creation with emptyDir
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
      subPath: html
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: "0.1"
        memory: "100Mi"
      limits:
        cpu: "0.2"
        memory: "200Mi"
  volumes:
  - name: nginx-storage
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: "0.1"
        memory: "100Mi"
      limits:
        cpu: "0.2"
        memory: "200Mi"
  - name: ubuntu
    image: ubuntu:18.04
    command: ["/bin/bash"]
    args: ["-c", "while true; do date >> /var/tmp/index.html; sleep 10;done"]
    volumeMounts:
    - name: nginx-storage
      mountPath: /var/tmp
    resources:
      requests:
        cpu: "0.1"
        memory: "100Mi"
      limits:
        cpu: "0.2"
        memory: "200Mi"
  volumes:
  - name: nginx-storage
    emptyDir: {}